version: '3.9'

services:
  chess-backend:
    build: .
    container_name: chess-backend
    restart: always
    networks:
      - caddy
    labels:
      caddy_0: api.chess.julianhartl.dev
      caddy_0.reverse_proxy: "{{upstreams 7999}}"
      caddy_1: ws.chess.julianhartl.dev
      caddy_1.reverse_proxy: "{{upstreams 8000}}"
    depends_on:
      - chess-db
  chess-db:
    image: postgres:15-alpine
    container_name: chess-db
    restart: always
    volumes:
      - chess_db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - caddy
volumes:
  chess_db:
networks:
  caddy:
    external: true