version: '3.9'

services:
  chess-backend:
    build: .
    container_name: chess-backend
    restart: always
    ports:
      - "7999:7999"
      - "8000:8000"
    networks:
      - caddy
    labels:
      caddy_0: chess.julianhartl.dev
      caddy.@ws.0_header: Connection *Upgrade*
      caddy.@ws.1_header: Upgrade websocket
      caddy.0_reverse_proxy: @ws {{upstreams 8000}}
      caddy.1_reverse_proxy: {{upstreams 7999}}
    depends_on:
      - chess-db
  chess-db:
    image: postgres:15-alpine
    container_name: chess-db
    restart: always
    volumes:
      - chess_db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - caddy
volumes:
  chess_db:
networks:
  caddy:
    external: true